name: check-food-on-weekdays

on:
  schedule:
    - cron: "0 7 * * 1-5"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        env:
          sender_email: ${{ secrets.SENDER_EMAIL }}
          sender_email_app_password: ${{ secrets.SENDER_EMAIL_APP_PASSWORD }}
          recipient_email: ${{ secrets.RECIPIENT_EMAIL }}
          url: ${{ secrets.URL }}
        run: python jalapeno.py